Blog_App/urls.py
from django.contrib import admin
from django.urls import path
from Blog_App.views import index, getauthor, getsingle, categoryPost, CreateBlog, MyPost, article_detail_view

app_name = 'Blog_App'

urlpatterns = [
    path('', index, name='index'),
    path('author/<name>', getauthor, name="post_author"),
    path('article/<int:id>', getsingle, name="single_post"),
    path('category/<name>', categoryPost, name="category_post"),
    path('create-article', CreateBlog.as_view(), name="create_blog"),
    path('list-article', MyPost.as_view(), name="my_blog"),
    path('article-detail/<slug:slug>', article_detail_view, name="blog_details")
]

Login_App/urls.py
from django.contrib import admin
from django.urls import path, include
from Login_App import views

app_name = 'Login_App'

urlpatterns = [
    #path('', home, name="home"),
    path('login', views.getLogin, name="login"),
    path('logout', views.getLogout, name="logout"),
    path('user-account', views.user_account, name="user_account"),
    path('register', views.user_register, name="user_register")
]

about/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('', home, name="home"),
]

personal_profile/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/app_login/create_blog.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Blog{% endblock %}
{% block css %}
<style>
    .profile_menu.active {
    transform: scale(1.03);
    background: linear-gradient(to right,rgba(8,179,141,0.05),rgba(56,105,168,0.05));
}
.profile_menu:nth-child(1) {
    border-radius: 4px 4px 0 0;
}
.profile_menu {
    margin: 2px;
    padding: 22px 10px 22px 20px;
    border: solid 1px rgba(44,134,143,0.25);
    border-top: 0;
    cursor: pointer;
    transition: all .3s;
    position: relative;
    z-index: 1000;
    overflow: hidden;
}
.profile_menu i {
    color: #2c868f;
    font-size: 1.5rem;
}
.profile_menu span {
    color: #236c98;
    font-size: 1.05em;
}
.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
  z-index: 2;
  color: #fff;
  background-color: linear-gradient(to right,rgba(8,179,141,0.05),rgba(56,105,168,0.05));
  border-color: linear-gradient(to right,rgba(8,179,141,0.05),rgba(56,105,168,0.05));
}
.top_line {
    width: 100%;
    height: 4px;
    margin: 0;
    padding: 0;
    background: linear-gradient(to right,#08b38d,#3869a8);
    position: absolute;
    top: 0;
    left: -0px;
}
.panel-default > .panel-heading {
    color: #333333;
    background: linear-gradient(to right,#08b38d,#3869a8);
    border-color: #ddd;
}
.image_holder {
    box-shadow: 0 1px 8px 0 rgb(44 134 143 / 30%);
    position: relative;
}
.image_holder p {
    margin: 0;
    padding: 0;
    background: linear-gradient(to right,#08b38d,#3869a8);
}
.bottom-line {
    width: 10%;
    height: 2px;
    position: absolute;
    bottom: -2px;
    right: 0;
}
.left-line {
    width: 2px;
    height: 10%;
    position: absolute;
    top: 0;
    left: -2px;
}
.right-line {
    width: 2px;
    height: 10%;
    position: absolute;
    bottom: 0;
    right: -2px;
}
.profile_image {
    width: 100%;
}
img {
    vertical-align: middle;
    border-style: none;
}
.avatar_holder {
    color: #145a82;
    margin: 20px;
    padding: 4px 8px !important;
    border-radius: 4px;
    background: white !important;
    box-shadow: 0 1px 4px 0 rgb(30 130 168 / 50%);
    position: absolute;
    top: 5px;
    right: 5px;
    cursor: pointer;
}
.avatar_holder {
    color: #145a82;
    margin: 20px;
    padding: 4px 8px !important;
    border-radius: 4px;
    background: white !important;
    box-shadow: 0 1px 4px 0 rgb(30 130 168 / 50%);
    position: absolute;
    top: 5px;
    right: 5px;
    cursor: pointer;
}
.profile_details_holder {
    width: 90%;
    margin-left: 10%;
    font-size: 1em;
    line-height: 2.1;
    color: #295f9a;
}
.icon_column {
    width: 10%;
    text-align: center;
}
.top-line {
    width: 10%;
    height: 2px;
    position: absolute;
    top: -2px;
    left: 0;
}
.detailsPan {
    color: #295f9a !important;
}
.text-right {
    text-align: right !important;
}
.btn:not(:disabled):not(.disabled) {
    cursor: pointer;
}
[type=reset], [type=submit], button, html [type=button] {
    -webkit-appearance: button;
}
.edit-password, .edit-button, .edit-password:hover, .edit-button:hover, .edit-password:focus, .edit-button:focus {
    font-size: .95em;
}
.blog_button, .blog_button:hover, .blog_button:focus {
    color: white;
    padding: 8px 30px;
    border-radius: 30px;
    font-size: 1em;
    background: linear-gradient(to right,#08b38d,#3869a8);
    text-transform: lowercase;
}
.profile_div {
    margin: 8px;
    margin-top: 0;
    padding: 10px;
    box-shadow: 0 1px 8px 0 rgb(44 134 143 / 30%);
}







</style>
{% endblock %}
{% block body_block %}
<div class="container-fluid" style="z-index:100;">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    {% include "app_login/profile_sidebar.html" %}
                </div>
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Write Article
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-offset-1 col-md-10">
                                    <div class="profile_div">
                                        <form method="POST" ENCTYPE="multipart/form-data">
                                            {{form|crispy}}
                                            {% csrf_token %}
                                            {{ form.media }}
                                            <button type="submit" class="btn btn-success btn-sm">Publish</button>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/app_login/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Blog-login{% endblock %}
{% block category %}
<div class="fh5co-menu">
    <div class="fh5co-box">
        <h3 class="heading">Menu</h3>
        <ul>
            {% for cat in categories %}
            <li><a href="{% url 'Blog_App:category_post' name=cat.name %}">{{ cat.name }}</a></li>
            {% endfor %}
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'Login_App:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'Login_App:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="fh5co-box">
        <h3 class="heading">Search</h3>
        <form action="#">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Type a keyword">
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block body_block %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Login here</h4>
                </div>
                <div class="panel-body">
                    <!--{% if messages %}-->
                    <!--{% for message in messages %}-->
                    <!--<div class="alert alert-danger" role="alert">{{message}}</div>-->
                    <!--{% endfor %}-->
                    <!--{% endif %}-->
                    <form action="" method="post">
                        {{ form|crispy}}
                        {% csrf_token %}
                        <!--<div class="form-group">-->
                            <!--<label for="username">Usernme</label>-->
                            <!--<input type="text" class="form-control" id="username" aria-describedby="emailHelp"-->
                                   <!--placeholder="username" name="user">-->

                        <!--</div>-->
                        <!--<div class="form-group">-->
                            <!--<label for="exampleInputPassword1">Password</label>-->
                            <!--<input type="password" class="form-control" id="exampleInputPassword1"-->
                                   <!--placeholder="Password" name="pass">-->
                        <!--</div>-->

                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                    <div class="row">
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-9">
                            <span>If you have no account, Please <a href="{% url 'Login_App:user_register' %}">Click</a> Here to create a new account</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/app_login/my_post.html
{% extends 'blog/base.html' %}
{% block title %}Blog{% endblock %}
{% block css %}
<style>
    .profile_menu.active {
    transform: scale(1.03);
    background: linear-gradient(to right,rgba(8,179,141,0.05),rgba(56,105,168,0.05));
}
.profile_menu:nth-child(1) {
    border-radius: 4px 4px 0 0;
}
.profile_menu {
    margin: 2px;
    padding: 22px 10px 22px 20px;
    border: solid 1px rgba(44,134,143,0.25);
    border-top: 0;
    cursor: pointer;
    transition: all .3s;
    position: relative;
    z-index: 1000;
    overflow: hidden;
}
.profile_menu i {
    color: #2c868f;
    font-size: 1.5rem;
}
.profile_menu span {
    color: #236c98;
    font-size: 1.05em;
}
.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
  z-index: 2;
  color: #fff;
  background-color: linear-gradient(to right,rgba(8,179,141,0.05),rgba(56,105,168,0.05));
  border-color: linear-gradient(to right,rgba(8,179,141,0.05),rgba(56,105,168,0.05));
}
.top_line {
    width: 100%;
    height: 4px;
    margin: 0;
    padding: 0;
    background: linear-gradient(to right,#08b38d,#3869a8);
    position: absolute;
    top: 0;
    left: -0px;
}
.panel-default > .panel-heading {
    color: #333333;
    background: linear-gradient(to right,#08b38d,#3869a8);
    border-color: #ddd;
}
.image_holder {
    box-shadow: 0 1px 8px 0 rgb(44 134 143 / 30%);
    position: relative;
}
.image_holder p {
    margin: 0;
    padding: 0;
    background: linear-gradient(to right,#08b38d,#3869a8);
}
.bottom-line {
    width: 10%;
    height: 2px;
    position: absolute;
    bottom: -2px;
    right: 0;
}
.left-line {
    width: 2px;
    height: 10%;
    position: absolute;
    top: 0;
    left: -2px;
}
.right-line {
    width: 2px;
    height: 10%;
    position: absolute;
    bottom: 0;
    right: -2px;
}
.profile_image {
    width: 100%;
}
img {
    vertical-align: middle;
    border-style: none;
}
.avatar_holder {
    color: #145a82;
    margin: 20px;
    padding: 4px 8px !important;
    border-radius: 4px;
    background: white !important;
    box-shadow: 0 1px 4px 0 rgb(30 130 168 / 50%);
    position: absolute;
    top: 5px;
    right: 5px;
    cursor: pointer;
}
.avatar_holder {
    color: #145a82;
    margin: 20px;
    padding: 4px 8px !important;
    border-radius: 4px;
    background: white !important;
    box-shadow: 0 1px 4px 0 rgb(30 130 168 / 50%);
    position: absolute;
    top: 5px;
    right: 5px;
    cursor: pointer;
}
.profile_details_holder {
    width: 90%;
    margin-left: 10%;
    font-size: 1em;
    line-height: 2.1;
    color: #295f9a;
}
.icon_column {
    width: 10%;
    text-align: center;
}
.top-line {
    width: 10%;
    height: 2px;
    position: absolute;
    top: -2px;
    left: 0;
}
.detailsPan {
    color: #295f9a !important;
}
.text-right {
    text-align: right !important;
}
.btn:not(:disabled):not(.disabled) {
    cursor: pointer;
}
[type=reset], [type=submit], button, html [type=button] {
    -webkit-appearance: button;
}
.edit-password, .edit-button, .edit-password:hover, .edit-button:hover, .edit-password:focus, .edit-button:focus {
    font-size: .95em;
}
.blog_button, .blog_button:hover, .blog_button:focus {
    color: white;
    padding: 8px 30px;
    border-radius: 30px;
    font-size: 1em;
    background: linear-gradient(to right,#08b38d,#3869a8);
    text-transform: lowercase;
}




</style>
{% endblock %}
{% block body_block %}
<div class="container-fluid" style="z-index:100;">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    {% include "app_login/profile_sidebar.html" %}
                </div>
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            My Article
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="panel panel-default">
                                        <table class="table">
                                            <tr>
                                                <th>SL</th>
                                                <th>Category</th>
                                                <th>Title</th>
                                                <th>Posted On</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for blog in user.post_author.all %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{blog.category}}</td>
                                                <td>{{ blog.title|truncatechars:50 }}</td>
                                                <td>{{ blog.publish_date }}</td>
                                                <td>
                                                    {% if blog.publish_status == 3 %}
                                                    <span>Publish</span>
                                                    {% elif blog.publish_status == 1 %}
                                                    <span>Pending</span>
                                                    {% elif blog.publish_status == 2 %}
                                                    <span>On Review</span>
                                                    {% else %}
                                                    <span>Draft</span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    <!--<button class="btn"-->
                                                    <!--data-toggle="modal" data-target="#largeShoes">-->
                                                    <!--<a href="{% url 'Blog_App:blog_details' slug=blog.slug %}"><i-->
                                                    <!--class="fa fa-eye"></i></a>-->
                                                    <a class="btn detailView" data-id={{ blog.slug }}><i
                                                            class="fa fa-eye"></i></a>
                                                    <!--</button>-->
                                                    <a href="" class="btn"><i class="fa fa-edit"></i></a>
                                                    <a href="" class="btn"><i class="fa fa-trash"></i></a>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Modal -->
<!-- The modal -->
<div class="modal" id="largeShoes" tabindex="-1" role="dialog" aria-labelledby="modalLabelLarge" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modalLabelLarge">Modal Title</h4>
            </div>

            <div class="modal-body">
                {{article.title}}
            </div>

        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    function openModal(){

    $('.modal').modal();
}
$(document).on('click','.detailView',function(){
    $('.modal').modal();
    const dataId = $(this).data("id");
    $.ajax({
        url: '/blog/article-detail/'+dataId,
        dataType: 'json',
        success: function (data) {
          console.log(data)
        }
      });
});



</script>
{% endblock %}

templates/app_login/profile_sidebar.html
<div class="list-group">
    <a href="{% url 'Login_App:user_account' %}" class="list-group-item profile_menu">
        <p class="top_line"></p>
        <i class="fa fa-user"></i>
        <span>Profile</span>
    </a>
    <a href="{% url 'Blog_App:create_blog' %}" class="list-group-item profile_menu">
       <i class="fa fa-edit"></i>
        <span> Write a New Article</span>
    </a>
    <a href="{% url 'Blog_App:my_blog' %}" class="list-group-item profile_menu">
        <i class="fa fa-pencil"></i>
        <span> My Article</span>
    </a>
    <a href="#" class="list-group-item profile_menu">Porta ac consectetur ac</a>
    <a href="#" class="list-group-item profile_menu">Vestibulum at eros</a>
</div>

templates/app_login/signup.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							<input type="email" name="email">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="text" name="password1">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="text" name="password2">
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>