Blog_App/urls.py
from django.contrib import admin
from django.urls import path
from Blog_App.views import index, getauthor, getsingle, categoryPost, CreateBlog, MyPost, article_detail_view

app_name = 'Blog_App'

urlpatterns = [
    path('', index, name='index'),
    path('author/<name>', getauthor, name="post_author"),
    path('article/<int:id>', getsingle, name="single_post"),
    path('category/<name>', categoryPost, name="category_post"),
    path('create-article', CreateBlog.as_view(), name="create_blog"),
    path('list-article', MyPost.as_view(), name="my_blog"),
    path('article-detail/<slug:slug>', article_detail_view, name="blog_details")
]

Login_App/urls.py
from django.contrib import admin
from django.urls import path, include
from Login_App import views

app_name = 'Login_App'

urlpatterns = [
    #path('', home, name="home"),
    path('login', views.getLogin, name="login"),
    path('logout', views.getLogout, name="logout"),
    path('user-account', views.user_account, name="user_account"),
    path('register', views.user_register, name="user_register")
]

about/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('', home, name="home"),
]

personal_profile/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', include('about.urls')),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Template by FREEHTML5.CO"/>
    <meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive"/>
    <meta name="author" content="FREEHTML5.CO"/>
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,700'
          rel='stylesheet' type='text/css'>
    <!-- Animate -->
    <link rel="stylesheet" href="{% static 'blog/css/animate.css' %}">
    <!-- Icomoon -->
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %} ">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">

    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"/>

    {% block css %}
    {% endblock %}

    <!-- Modernizr JS -->
    <script src="{% static 'blog/js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]-->
    <script src="{% static 'blog/js/respond.min.js' %}"></script>
    <!--[endif]-->
    <style type="text/css">
		#fh5co-offcanvas {
    width: auto;
}
#fh5co-offcanvas .fh5co-menu, #fh5co-offcanvas .fh5co-bio {
    width: auto;
    padding: 50px;
}
* {
    font-family: 'Open Sans',serif;
    margin: 0;
    padding: 0;
}

    </style>
</head>
<body>
<div id="fh5co-offcanvas">
    <a href="#" class="fh5co-close-offcanvas js-fh5co-close-offcanvas"><span><i
            class="icon-cross3"></i> <span>Close</span></span></a>
    {% block profile %}
    {% endblock %}
    {% block category %}
    {% endblock %}
</div>
<!-- END #fh5co-offcanvas -->
<header id="fh5co-header">
    <div class="container-fluid">

        <div class="row">
            <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
            <ul class="fh5co-social">
                <li><a href="#"><i class="icon-twitter"></i></a></li>
                <li><a href="#"><i class="icon-facebook"></i></a></li>
                <li><a href="#"><i class="icon-instagram"></i></a></li>
            </ul>
            <div class="col-lg-12 col-md-12 text-center">
                <h1 id="fh5co-logo"><a href="{% url 'Blog_App:index' %}">Learn The Right Way</a></h1>
            </div>

        </div>

    </div>
</header>
<!-- END #fh5co-header -->
<div class="container-fluid">
    <div class="row fh5co-post-entry">
        {% block body_block %}
        {% endblock %}
    </div>
</div>

<footer id="fh5co-footer">
    <p>
        <small>&copy; 2016. Magazine Free HTML5. All Rights Reserverd. <br> Designed by <a href="http://freehtml5.co"
                                                                                           target="_blank">FREEHTML5.co</a>
            Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small>
    </p>
</footer>


<!-- jQuery -->
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'blog/js/jquery.easing.1.3.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'blog/js/jquery.waypoints.min.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'blog/js/main.js' %}"></script>
{% block js %}
{% endblock %}

</body>
</html>

templates/blog/category_post.html
{% extends 'blog/base.html' %}
{% block title %}Blog-category post{% endblock %}
{% block category %}
<div class="fh5co-menu">
    <div class="fh5co-box">
        <h3 class="heading">Menu</h3>
        <ul>
            {% for cat in categories %}
            <li><a href="{% url 'Blog_App:category_post' name=cat.name %}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="fh5co-box">
        <h3 class="heading">Search</h3>
        <form action="#">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Type a keyword">
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block body_block %}

{% for p in posts %}
<article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
    <figure>
        <!--<a href="single.html"><img src="/media/{{ p.articate_image }}" alt="Image" class="img-responsive"></a>-->
        {% if p.articate_image %}
        <a href="{% url 'Blog_App:single_post' id=p.id %}"><img src="{{ p.articate_image.thumbnail.url }}" alt="Image"
                                                                class="img-responsive"></a>
        {% endif %}
    </figure>
    <span class="fh5co-meta"><a href="{% url 'Blog_App:category_post' name=p.category.name %}">{{ p.category.name }}</a></span>
    <h2 class="fh5co-article-title"><a href="{% url 'Blog_App:single_post' id=p.id %}">{{ p.title|truncatechars:50 }}</a></h2>
    <span class="fh5co-meta fh5co-date">{{ p.publish_date|date:'H M Y' }}</span>
</article>
{% endfor %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?p=1">&laquo; first</a>
            <a href="?p={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?p={{ posts.next_page_number }}">next</a>
            <a href="?p={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}Blog{% endblock %}
{% block category %}
<div class="fh5co-menu">
    <div class="fh5co-box">
        <h3 class="heading">Menu</h3>
        <ul>
            {% for cat in categories %}
            <li><a href="{% url 'Blog_App:category_post' name=cat.name %}">{{ cat.name }}</a></li>
            {% endfor %}
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'Login_App:user_account' %}">User Profile</a></li>
            <li><a href="{% url 'Login_App:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'Login_App:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="fh5co-box">
        <h3 class="heading">Search</h3>
        <form action="" method="GET">
            <div class="form-group">
                <input type="text" name="search" class="form-control" placeholder="Type a keyword"
                       value="{{ request.GET.search}}">
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block body_block %}
{% for p in blogs %}
<article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
    <figure>
        {% if p.articate_image %}
        <a href="{% url 'Blog_App:single_post' id=p.id %}"><img src="{{ p.articate_image.thumbnail.url }}" alt="Image"
                                                                class="img-responsive"></a>
        <span class="fh5co-meta"><a href="{% url 'Blog_App:category_post' name=p.category.name %}">{{ p.category.name }}</a></span>
        <h4 class="fh5co-article-title"><a href="{% url 'Blog_App:single_post' id=p.id %}">{{ p.title|truncatechars:50 }}</a></h4>
        <h5><span>Created By: </span>&nbsp;<a href="{% url 'Blog_App:post_author' name=p.author %}">{{p.author}}</a></h5>
        <span class="fh5co-meta fh5co-date">{{ p.publish_date|date:'H M Y' }}</span>
        {% endif %}
    </figure>
</article>
{% endfor %}
{% endblock %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Blog-login{% endblock %}
{% block category %}

{% endblock %}
{% block body_block %}

{% endblock %}

templates/blog/profile.html
{% extends 'blog/base.html' %}
{% block title %}Profile{% endblock %}
{% block css %}

{% endblock %}
{% block profile %}
<div class="fh5co-bio">
    <figure>
        <img src="{{ auth.user_profile.profile_pic.url }}" alt="{{ auth }}" class="img-responsive">
    </figure>
    <h3 class="heading">About Me</h3>
    <h4>{{ auth }}</h4>
    <p>{{ auth.email }}</p>
    <p>{{ auth.user_profile.about|safe }}</p>
    <ul class="fh5co-social">
        <li><a href="#"><i class="icon-twitter"></i></a></li>
        <li><a href="#"><i class="icon-facebook"></i></a></li>
        <li><a href="#"><i class="icon-instagram"></i></a></li>
    </ul>
</div>
{% endblock %}
{% block body_block %}
{% for p in posts %}
<article class="col-lg-3 col-md-3 col-sm-3 col-xs-6 col-xxs-12 animate-box">
    <figure>
        <!--<a href="single.html"><img src="/media/{{ p.articate_image }}" alt="Image" class="img-responsive"></a>-->
        {% if p.articate_image %}
        <a href="{% url 'Blog_App:single_post' id=p.id %}"><img src="{{ p.articate_image.thumbnail.url }}" alt="Image"
                                                                class="img-responsive"></a>
        {% endif %}
    </figure>
    <span class="fh5co-meta"><a href="{% url 'Blog_App:category_post' name=p.category.name %}">{{ p.category.name }}</a></span>
    <h2 class="fh5co-article-title"><a href="{% url 'Blog_App:single_post' id=p.id %}">{{ p.title|truncatechars:50 }}</a></h2>
    <span class="fh5co-meta fh5co-date">{{ p.publish_date|date:'H M Y' }}</span>
</article>
{% endfor %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?p=1">&laquo; first</a>
            <a href="?p={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?p={{ posts.next_page_number }}">next</a>
            <a href="?p={{ posts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Blog-login{% endblock %}
{% block category %}
<div class="fh5co-menu">
    <div class="fh5co-box">
        <h3 class="heading">Menu</h3>
        <ul>
            {% for cat in categories %}
            <li><a href="{% url 'Blog_App:category_post' name=cat.name %}">{{ cat.name }}</a></li>
            {% endfor %}
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'Blog_App:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'Blog_App:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="fh5co-box">
        <h3 class="heading">Search</h3>
        <form action="#">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Type a keyword">
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block body_block %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Register here</h4>
                </div>
                <div class="panel-body">
                    {% if registered %}
                    <div class="alert alert-success" role="alert">Registered Successfully</div>
                    {% endif %}

                    <form action="" method="post">
                        {{ form|crispy}}
                        {% csrf_token %}

                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/single.html
{% extends 'blog/base.html' %}
{% block title %}Blog{% endblock %}
{% block css %}
{% endblock %}
{% block profile %}
<!--<div class="fh5co-bio">-->
<!--<figure>-->
<!--<img src="{{ post.post_author.author_image.thumbnail.url}}" alt="Free HTML5 Bootstrap Template" class="img-responsive">-->
<!--</figure>-->
<!--<h3 class="heading">About Me</h3>-->
<!--<h2>{{ post.author.name }}</h2>-->
<!--<p>{{ post.article_author.details|safe }}</p>-->
<!--<ul class="fh5co-social">-->
<!--<li><a href="#"><i class="icon-twitter"></i></a></li>-->
<!--<li><a href="#"><i class="icon-facebook"></i></a></li>-->
<!--<li><a href="#"><i class="icon-instagram"></i></a></li>-->
<!--</ul>-->
<!--</div>-->
{% endblock %}
{% block body_block %}
{% if post.id > first.id %}
<a href="{% url 'Blog_App:single_post' id=post.id|add:'-1' %}" class="fh5co-post-prev"><span><i
        class="icon-chevron-left"></i> Prev</span></a>
{% endif %}

{% if post.id < last.id %}
<a href="{% url 'Blog_App:single_post' id=post.id|add:'+1' %}" class="fh5co-post-next"><span>Next <i
        class="icon-chevron-right"></i></span></a>
{% endif %}
<div class="container-fluid">
    <div class="row fh5co-post-entry single-entry">
        <article
                class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12 col-xs-offset-0">
            <figure class="animate-box justify-content-center">
                <img src="{{ post.articate_image.large.url}}" alt="Image" class="img-responsive">
            </figure>
            <span class="fh5co-meta animate-box"><a href="{% url 'Blog_App:category_post' name=post.category.name %}">{{ post.category.name }}</a></span>
            <h2 class="fh5co-article-title animate-box"><a href="{% url 'Blog_App:single_post' id=post.id %}">{{ post.title }}</a></h2>
            <span class="fh5co-meta fh5co-date animate-box">{{ post.publish_date|date:'H M Y' }}</span>

            <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-left content-article">
                <div class="row">
                    <div class="col-lg-12 cp-r animate-box">
                        {{ post.body|safe }}
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
<div class="container">
    <h3 class="well">Related Post</h3>
    <div class="row">
        {% for post in related %}
        <div class="col-md-3">
            <a href="{% url 'Blog_App:single_post' id=post.id %}">
                <figure class="animate-box justify-content-center">
                    <img src="{{ post.articate_image.thumbnail.url}}" alt="Image" class="img-responsive">
                </figure>
            </a>
            <h4 class="fh5co-article-title animate-box"><a href="{% url 'Blog_App:single_post' id=post.id %}">{{ post.title|truncatechars:25}}</a></h4>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}